referenceless_regression_metric:
  class_path: comet.models.ReferencelessRegression
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-05
    learning_rate: 3.1e-05
    layerwise_decay: 0.95
    encoder_model: BERT
    pretrained_model: gbert-data
    pool: avg
    layer: mix
    dropout: 0.15
    batch_size: 4
    train_data: data/2017-18-19-de-da.csv
    validation_data: data/2020-de-da-dev.csv
    hidden_sizes:
      - 2048
      - 1024
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml